### ISSUE TITLE
my work on Jan, 2019

### ISSUE THREAD

**Issue by iliyaYuan** [iliyaYuan/html_study#1]
# tasks

- [ ] complete the study of base HTML
- [ ] make a beautiful page
- [ ] know some base knowledge of CSS

**Comment by iliyaYuan** [comment]
In fact, this month I didn't complete any of my plan, just for my laziness.
I can't make my heart down and I often think of sweet scenes with my ex.
ma..... I know this is not correct. can't control my own mind.  I'm alone.
But best wish to her! from now on. I need to stand up to see the sunrise.
Don't stop! Maybe better future is waiting for my arrival.
Come on!
